'use client';
import { useMemo, useState } from 'react';
import { ArrowUpDown } from 'lucide-react';
import { LiveBoundary, useLiveResource, duration } from '@/components/v2/LiveData';
import AnalyticsFilters, { toIsoDate, type AnalyticsFilterValue, type DeviceCount } from '@/components/AnalyticsFilters';
import { useI18n } from '@/components/i18n';
import { pageDisplayName, pagePathOf } from '@/lib/page-label';

type Point={id:string;page:string;pageName?:string|null;pageTitle?:string|null;event_type:string;device?:string|null;x:number|null;y:number|null;document_x?:number|null;document_y?:number|null;document_width?:number|null;document_height?:number|null;viewport_width:number|null;viewport_height:number|null;element_text?:string|null;element_key?:string|null;section?:string|null;created_at?:string};
type ElementRow={key:string;page:string;label:string;clicks:number;rageClicks:number;deadClicks:number;confusionScore:number;signal:string};
type PageRow={pagePath:string;pageName?:string|null;pageTitle?:string|null;pageUrl?:string|null;scrollMax:number};
type SectionRow={page:string;section:string;views:number;attentionMs:number;clicks:number;rageClicks:number;deadClicks:number};
type DeviceRow=DeviceCount&{points?:number};
type Issue={key:string;type:string;page:string;element:string;occurrences:number;severity?:string;priorityScore?:number};
type Data={pages:PageRow[];devices:DeviceRow[];points:Point[];elements:ElementRow[];scroll:{page:string;pageName?:string|null;pageTitle?:string|null;scrollMax:number}[];sections:SectionRow[];issues:Issue[]};
const initial:AnalyticsFilterValue={from:'',to:'',compare:'previous',page:'',device:''};

export default function Heatmaps(){
 const {lang,t}=useI18n();const vi=lang==='vi';const [filter,setFilter]=useState(initial);const [mode,setMode]=useState<'click'|'rage_click'|'dead_click'|'scroll'|'attention'>('click');const [focusPoint,setFocusPoint]=useState<Point|null>(null);const [sortBy,setSortBy]=useState('priority');
 const query=useMemo(()=>{const q=new URLSearchParams();const f=toIsoDate(filter.from),to=toIsoDate(filter.to);if(f)q.set('from',f);if(to)q.set('to',to);if(filter.page)q.set('page',filter.page);if(filter.device)q.set('device',filter.device);q.set('compare',filter.compare);return q.toString()},[filter]);
 const resource=useLiveResource<Data>('heatmaps-v2',query);const data=resource.data;
 const availableDevices=(data?.devices||[]).filter(d=>d.count>0||Number(d.points||0)>0);
 const fallbackDevice=availableDevices.find(d=>d.name==='desktop')?.name||availableDevices[0]?.name||'';
 const effectivePage=filter.page||((data?.pages||[]).length?pagePathOf(data?.pages?.[0]):'');
 const effectiveDevice=filter.device||fallbackDevice;
 const rawPoints=(data?.points||[]).filter(p=>(!effectivePage||p.page===effectivePage)&&(!effectiveDevice||p.device===effectiveDevice));
 const points=rawPoints.filter(p=>mode==='click'?['click','rage_click','dead_click'].includes(p.event_type):p.event_type===mode).filter(p=>(p.document_x!=null&&p.document_y!=null&&p.document_width&&p.document_height)||(p.x!=null&&p.y!=null&&p.viewport_width&&p.viewport_height)).slice(0,500);
 const maxAttention=Math.max(1,...(data?.sections||[]).map(x=>x.attentionMs));
 const selectedPage=(data?.pages||[]).find(p=>pagePathOf(p)===effectivePage);const pageTitle=effectivePage?pageDisplayName(selectedPage||effectivePage,lang):(vi?'Tất cả trang':'All pages');
 const deviceName=(name:string)=>name==='mobile'?(vi?'Điện thoại':'Mobile'):name==='tablet'?(vi?'Máy tính bảng':'Tablet'):(vi?'Máy tính':'Desktop');
 const plotPoint=(p:Point)=>{const doc=Boolean(p.document_x!=null&&p.document_y!=null&&p.document_width&&p.document_height);const x=doc?(p.document_x!/(p.document_width||1))*100:(p.x!/(p.viewport_width||1))*100;const y=doc?(p.document_y!/(p.document_height||1))*100:(p.y!/(p.viewport_height||1))*100;return{x:Math.max(0,Math.min(100,x)),y:Math.max(0,Math.min(100,y))}};
 const dims=points.reduce((a,p)=>({w:Math.max(a.w,Number(p.document_width||p.viewport_width||0)),h:Math.max(a.h,Number(p.document_height||p.viewport_height||0))}),{w:0,h:0});const plotHeight=dims.w&&dims.h?Math.max(520,Math.min(1400,Math.round(900*dims.h/dims.w))):620;
 const elementRows=[...(data?.elements||[])].sort((a,b)=>sortBy==='clicks'?b.clicks-a.clicks:sortBy==='rage'?b.rageClicks-a.rageClicks:sortBy==='dead'?b.deadClicks-a.deadClicks:(b.deadClicks*3+b.rageClicks*2+b.confusionScore)-(a.deadClicks*3+a.rageClicks*2+a.confusionScore));
 const severity=(i:Issue)=>i.severity||((i.type==='task_fail'||i.occurrences>=8)?'CRITICAL':i.occurrences>=4?'HIGH':i.occurrences>=2?'MEDIUM':'LOW');
 const priority=(i:Issue)=>i.priorityScore??(i.occurrences*(i.type==='dead_click'?3:i.type==='rage_click'?2:3));
 const issues=[...(data?.issues||[])].sort((a,b)=>priority(b)-priority(a));
 return <LiveBoundary title={t('heatmaps')} {...resource} subtitle={vi?'Bản đồ tương tác theo từng trang, nút nhấn, cuộn trang và mức chú ý.':'Page-specific interaction heatmaps.'}>
  <AnalyticsFilters value={filter} onChange={setFilter} pages={data?.pages||[]} deviceCounts={data?.devices||[]}/>
  <div className="heatmap-mode-tabs">{([['click',vi?'Lượt nhấn':'Clicks'],['attention',vi?'Mức chú ý':'Attention'],['scroll',vi?'Cuộn trang':'Scroll'],['rage_click',vi?'Click liên tục':'Rage clicks'],['dead_click',vi?'Click không phản hồi':'Dead clicks']] as const).map(([key,label])=><button key={key} className={mode===key?'active':''} onClick={()=>{setMode(key);setFocusPoint(null)}}>{label}</button>)}</div>
  <div className="grid grid2 heatmap-layout">
   <section className="card heatmap-canvas-card"><div className="card-header"><div><h2>{mode==='attention'?(vi?'Bản đồ mức chú ý':'Attention map'):mode==='scroll'?(vi?'Độ sâu cuộn trang':'Scroll depth'):(vi?'Bản đồ tương tác':'Interaction heatmap')}</h2><p><b>{pageTitle}</b>{effectivePage&&<span> · {effectivePage}</span>}{effectiveDevice&&<span> · {deviceName(effectiveDevice)}</span>}</p></div></div>
    {mode==='scroll'?<div className="scroll-heat-list">{(data?.scroll||[]).length?(data?.scroll||[]).filter(r=>!effectivePage||r.page===effectivePage).map(row=><div className="scroll-heat-row" key={row.page}><div><b>{pageDisplayName({pagePath:row.page,pageName:row.pageName,pageTitle:row.pageTitle},lang)}</b><span>{row.scrollMax?`${row.scrollMax}%`:'--'}</span></div><div className="scroll-track"><i style={{height:`${Math.max(0,Math.min(100,row.scrollMax||0))}%`}}/></div></div>):<Empty vi={vi} textVi="Chưa có dữ liệu cuộn trang." textEn="No scroll data yet."/>}</div>
    :mode==='attention'?<div className="attention-heat-list">{(data?.sections||[]).filter(r=>!effectivePage||r.page===effectivePage).length?(data?.sections||[]).filter(r=>!effectivePage||r.page===effectivePage).map(row=><div className="attention-section-row" key={`${row.page}-${row.section}`}><div><b>{row.section}</b><small>{pageDisplayName(row.page,lang)}</small></div><div className="attention-section-bar"><i style={{width:`${Math.max(4,Math.round(row.attentionMs/maxAttention*100))}%`}}/></div><strong>{row.attentionMs?duration(row.attentionMs):'--'}</strong></div>):<Empty vi={vi} textVi="Chưa có dữ liệu mức chú ý theo khu vực." textEn="No section attention yet."/>}</div>
    :<div className="heatmap-plot" style={{minHeight:plotHeight}}>{focusPoint&&<PointInspector point={focusPoint} lang={lang}/>} {points.length?points.map(p=>{const pos=plotPoint(p);const label=`${eventLabel(p.event_type,vi)} · ${p.element_text||p.element_key||pageDisplayName({pagePath:p.page,pageName:p.pageName,pageTitle:p.pageTitle},lang)}`;return <button type="button" key={p.id} className={`heat-dot ${p.event_type}`} style={{left:`${pos.x}%`,top:`${pos.y}%`}} title={label} aria-label={label} onMouseEnter={()=>setFocusPoint(p)} onFocus={()=>setFocusPoint(p)} onClick={()=>setFocusPoint(p)}/>;}):<Empty vi={vi} textVi="Chưa có điểm tương tác cho trang và thiết bị đang lọc." textEn="No interaction points for the selected filters."/>}</div>}
   </section>
   <section className="card account-panel"><div className="card-header"><div><h2>{vi?'Xếp hạng nút / phần tử':'Button / element ranking'}</h2><p>{vi?'Ưu tiên phần tử cần chú ý để xử lý nhanh.':'Prioritize elements that need attention.'}</p></div><label className="element-sort"><ArrowUpDown size={15}/><select value={sortBy} onChange={e=>setSortBy(e.target.value)}><option value="priority">{vi?'Ưu tiên cần xử lý':'Priority'}</option><option value="dead">{vi?'Không phản hồi nhiều nhất':'Most dead clicks'}</option><option value="rage">{vi?'Click liên tục nhiều nhất':'Most rage clicks'}</option><option value="clicks">{vi?'Nhiều lượt nhấn nhất':'Most clicks'}</option></select></label></div><div className="element-ranking">{elementRows.length?elementRows.slice(0,16).map((e,i)=><div className="element-row" key={e.key}><div className="element-rank">{i+1}</div><div className="element-copy"><b>{e.label || (vi?'Phần tử chưa có nhãn':'Unlabelled element')}</b><small>{pageDisplayName(e.page,lang)} · {e.page}</small></div><div className="element-metrics"><span>{e.clicks} {vi?'lượt nhấn':'clicks'}</span><span>{e.rageClicks} {vi?'liên tục':'rage'}</span><span>{e.deadClicks} {vi?'không phản hồi':'dead'}</span></div><span className={`pill ${e.confusionScore>2?'high':e.confusionScore>0?'medium':'good'}`}>{e.confusionScore>2?(vi?'Cần ưu tiên':'Priority'):e.confusionScore>0?(vi?'Cần xem':'Review'):(vi?'Ổn':'Healthy')}</span></div>):<Empty vi={vi} textVi="Chưa có dữ liệu phần tử." textEn="No element data yet."/>}</div></section>
  </div>
  <section id="ux-issues" className="card account-panel"><div className="card-header"><div><h2>{vi?'Vấn đề UX ghi nhận':'Observed UX issues'}</h2><p>{vi?'Chỉ hiển thị tín hiệu tiêu cực, xếp theo mức độ ưu tiên xử lý.':'Negative UX signals ranked by remediation priority.'}</p></div></div><div className="account-table-wrap"><table className="account-table"><thead><tr><th>{vi?'Mức độ':'Severity'}</th><th>{vi?'Loại':'Type'}</th><th>{vi?'Trang':'Page'}</th><th>{vi?'Phần tử':'Element'}</th><th>{vi?'Số lần':'Occurrences'}</th><th>{vi?'Ưu tiên':'Priority'}</th></tr></thead><tbody>{issues.map(x=>{const sev=severity(x);return <tr key={x.key}><td><span className={`pill ${sev==='CRITICAL'||sev==='HIGH'?'high':sev==='MEDIUM'?'medium':'good'}`}>{sev==='CRITICAL'?(vi?'Nghiêm trọng':'Critical'):sev==='HIGH'?(vi?'Cao':'High'):sev==='MEDIUM'?(vi?'Trung bình':'Medium'):(vi?'Thấp':'Low')}</span></td><td>{eventLabel(x.type,vi)}</td><td>{pageDisplayName(x.page,lang)}<small className="page-path-inline">{x.page}</small></td><td>{x.element}</td><td>{x.occurrences}</td><td><b>{priority(x)}</b></td></tr>})}</tbody></table></div></section>
 </LiveBoundary>;
}
function eventLabel(type:string,vi:boolean){const m:Record<string,[string,string]>={click:['Lượt nhấn','Click'],rage_click:['Click liên tục','Rage click'],dead_click:['Click không phản hồi','Dead click'],task_error:['Lỗi tác vụ','Task error'],task_fail:['Tác vụ thất bại','Task failed'],task_abandon:['Bỏ dở tác vụ','Task abandoned']};return m[type]?.[vi?0:1]||type}
function Empty({vi,textVi,textEn}:{vi:boolean;textVi:string;textEn:string}){return <div className="heatmap-selection-empty"><strong>--</strong><p>{vi?textVi:textEn}</p></div>}
function PointInspector({point,lang}:{point:Point;lang:'en'|'vi'}){const vi=lang==='vi';return <div className="heatmap-point-inspector"><b>{point.element_text||point.element_key||(vi?'Khu vực trang':'Page area')}</b><span>{pageDisplayName({pagePath:point.page,pageName:point.pageName,pageTitle:point.pageTitle},lang)} · {point.page}</span>{point.section&&<span>{vi?'Khu vực':'Section'}: {point.section}</span>}<small>{eventLabel(point.event_type,vi)} · {point.device||'--'}</small></div>}
