"use client";
import React, {createContext, useContext, useEffect, useMemo, useState} from "react";

type Lang = "en" | "vi";
type Dict = Record<string, string>;

const en: Dict = {
  analyze:"Analyze", overview:"Overview", analytics:"Analytics", heatmaps:"Heatmaps", sessions:"Sessions", tasks:"Tasks", feedback:"Feedback", funnels:"Funnels", ai:"AI Analyst", sandbox:"Tracking Sandbox",
  workspace:"Workspace", productExperience:"Product Experience", demoDataset:"Demo dataset · Sep 1–30", trial:"TRIAL · UX INTELLIGENCE DEMO",
  overviewTitle:"Product experience overview", overviewSubtitle:"Understand where users spend time, where they struggle, and what deserves UX attention first.", last30:"Last 30 days", last7:"Last 7 days",
  uxHealth:"UX Health", activeUsers:"Active users", activeTime:"Active time", taskSuccess:"Task success", previousPeriod:"vs previous period",
  userAttention:"User attention", attentionSubtitle:"Active time compared with the previous period.", activeTimeLabel:"Active time", avgAttention:"Avg. attention", uxHealthSubtitle:"A composite view of task efficiency and friction.", uxScore:"UX score", frictionEvents:"Friction events",
  taskEfficiency:"Task efficiency", taskEfficiencySubtitle:"Median completion time across important user flows.", deviceMix:"Device mix", deviceMixSubtitle:"Where UX friction is concentrated.", mobile:"Mobile", desktop:"Desktop", tablet:"Tablet",
  uxPriorities:"UX priorities", uxPrioritySubtitle:"Impact × evidence × confidence.", high:"HIGH", medium:"MEDIUM", mobileCheckout:"Mobile checkout friction", pricingHesitation:"Pricing comparison hesitation", investigate:"Investigate", viewHeatmap:"View heatmap",
  pageAttention:"Page attention ranking", pageAttentionSubtitle:"Prioritize attention with exit and friction context.", views:"Views", dwell:"Dwell", exit:"Exit", activeTimeShort:"Active time", attentionFilter:"Active time",
  analyticsTitle:"Analytics", analyticsSubtitle:"Traffic, attention and efficiency in one view.", allDevices:"All devices", activeUsersAttention:"Active users & attention", activeUsersAttentionSubtitle:"Daily active users and average attention.", attentionMix:"Attention mix", attentionMixSubtitle:"Where active time is concentrated.", pageViews:"Page views", avgDwell:"Avg. dwell time", exitRate:"Exit rate",
  heatmapsTitle:"Heatmaps", heatmapsSubtitle:"Click, scroll and attention signals across page sections.", attention:"Attention", clicks:"Clicks", scroll:"Scroll", rageClicks:"Rage clicks", deadClicks:"Dead clicks", attentionHeatmap:"Attention heatmap", attentionHeatmapSubtitle:"Hotter areas indicate longer active attention.", sectionAttention:"Section attention", sectionAttentionSubtitle:"Ranked by active time.", designSignal:"Design signal", designSignalText:"Feature comparison receives 4× more attention than the primary CTA.", rageClickLabel:"Rage clicks", deadClickLabel:"Dead clicks", scrollDepth:"Scroll depth", paymentCta:"Payment CTA", planCards:"Plan cards", pricingPage:"Pricing page",
  sessionsTitle:"Sessions", sessionsSubtitle:"Connect individual journeys to friction and task outcomes.", filterSessions:"Filter sessions", sessionExplorer:"Session explorer", sessionExplorerSubtitle:"Select a session to inspect the journey.", session:"Session", device:"Device", location:"Location", duration:"Duration", lastStep:"Last step", signal:"Signal", healthy:"Healthy", replay:"Replay", replaySubtitle:"Mobile · Vietnam · 4m 32s", playReplay:"Play replay", friction:"FRICTION", paymentHesitation:"Payment hesitation", paymentHesitationText:"1m 28s on Payment, two backtracks and repeated clicks before exit.",
  tasksTitle:"Task efficiency", tasksSubtitle:"Measure speed, success, backtracking and errors across critical flows.", checkout:"Checkout", signup:"Signup", contact:"Contact", medianCompletion:"Median completion", backtracking:"Backtracking", errorRate:"Error rate", timePerStep:"Time per task step", timePerStepSubtitle:"Payment is the dominant time sink.", seconds:"Seconds", stepSuccess:"Step success", stepSuccessSubtitle:"Where users fail to progress.", paymentSlow:"Payment step is 2.8× slower", paymentSlowText:"63% of total task time is spent here. Inspect replay and heatmap before redesign.",
  feedbackTitle:"Feedback", feedbackSubtitle:"Combine survey responses with the behavioral context behind them.", createSurvey:"Create survey", csat:"CSAT", nps:"NPS", ces:"CES", recentFeedback:"Recent feedback", recentFeedbackSubtitle:"Feedback tied to page and journey context.", negative:"Negative", positive:"Positive", neutral:"Neutral", negativeConcentration:"Negative feedback concentration", negativeConcentrationSubtitle:"Where qualitative friction clusters.",
  funnelsTitle:"Funnels", funnelsSubtitle:"See where critical journeys lose momentum.", createFunnel:"+ Create funnel", checkoutConversion:"Checkout conversion", checkoutConversionSubtitle:"10,000 users entered this journey.", dropOff:"Drop-off", dropOffSubtitle:"Conversion between steps.", bottleneck:"BOTTLENECK", productContact:"Product → Contact", productContactText:"82% of users disappear before Contact. Investigate pricing attention and CTA visibility.",
  aiTitle:"AI Analyst", aiSubtitle:"Turn behavior signals into prioritized UX decisions with an evidence chain.", runAudit:"Run UX audit", topPriorities:"Top UX priorities", topPrioritiesSubtitle:"Ranked by impact × evidence × confidence.", confidence:"CONFIDENCE", recommendedAction:"Recommended action", inspectSessions:"Inspect sessions", inspectHeatmap:"Inspect heatmap", evidenceChain:"Evidence chain", evidenceChainSubtitle:"Trace every recommendation to observable behavior.", page:"Page", section:"Section", task:"Task",
  pricing:"Pricing", productDetail:"Product detail", homepage:"Homepage", checkoutPage:"Checkout", contactPage:"Contact", featureComparison:"Feature comparison", planComparison:"Plan comparison", faq:"FAQ", primaryCta:"Primary CTA", payment:"Payment", shipping:"Shipping", cart:"Cart", success:"Success",
  electronic:"Electronic", electronicSub:"Mobile, Earbuds, TV", fashion:"Fashion", fashionSub:"Tshirt, Jeans, Shoes", decor:"Decor", decorSub:"Fine Art, Dining", sports:"Sports", sportsSub:"Football, Cricket Kit",
  vietnam:"Vietnam", singapore:"Singapore", iphone:"Mobile · iPhone", chrome:"Desktop · Chrome", android:"Mobile · Android", safari:"Desktop · Safari", healthySignal:"Healthy",
  sandboxTitle:"Tracking Sandbox", sandboxSubtitle:"Send controlled events through the real Datatalk backend without creating a customer project.", liveData:"Live sandbox data", demoData:"Demo data", eventCount:"Events", sessionCount:"Sessions", activeTimeSandbox:"Active time", sectionAttentionSandbox:"Section attention", taskSuccessSandbox:"Task success", seedScenario:"Seed realistic scenario", resetSandbox:"Reset sandbox", sessionControls:"Session", interactionControls:"Interactions", attentionControls:"Attention", taskControls:"Task", feedbackControls:"Feedback", startSession:"Start session", endSession:"End session", pageView:"Page view", sectionView:"Section view", heartbeat30:"Heartbeat +30s", clickEvent:"Click", rageClickEvent:"Rage click", deadClickEvent:"Dead click", scroll72:"Scroll 72%", taskStart:"Task start", taskStep:"Task step", taskError:"Task error", taskBacktrack:"Backtrack", taskComplete:"Task complete", sendFeedback:"Send feedback", clearLog:"Clear log", eventLog:"Event log", noEvents:"No live events yet. Start a session or seed the scenario.", backendStatus:"Backend connection", backendLive:"Backend v1.3.5 · live", trialProject:"Internal trial sandbox", topPage:"Top page", topSection:"Top section", openSandbox:"Open sandbox"
};

const vi: Dict = {
  analyze:"Phân tích", overview:"Tổng quan", analytics:"Phân tích dữ liệu", heatmaps:"Heatmap", sessions:"Phiên truy cập", tasks:"Hiệu quả tác vụ", feedback:"Phản hồi", funnels:"Phễu chuyển đổi", ai:"AI Analyst", sandbox:"Tracking Sandbox",
  workspace:"Workspace", productExperience:"Trải nghiệm sản phẩm", demoDataset:"Dữ liệu mẫu · 1–30/09", trial:"BẢN DÙNG THỬ · UX INTELLIGENCE",
  overviewTitle:"Tổng quan trải nghiệm sản phẩm", overviewSubtitle:"Hiểu người dùng dành thời gian ở đâu, gặp khó khăn ở đâu và vấn đề UX nào cần ưu tiên.", last30:"30 ngày qua", last7:"7 ngày qua",
  uxHealth:"Sức khỏe UX", activeUsers:"Người dùng hoạt động", activeTime:"Thời gian hoạt động", taskSuccess:"Tỷ lệ hoàn thành tác vụ", previousPeriod:"so với kỳ trước",
  userAttention:"Mức độ chú ý của người dùng", attentionSubtitle:"Thời gian hoạt động so với kỳ trước.", activeTimeLabel:"Thời gian hoạt động", avgAttention:"Thời gian chú ý TB", uxHealthSubtitle:"Chỉ số tổng hợp về hiệu quả tác vụ và friction.", uxScore:"Điểm UX", frictionEvents:"Sự kiện friction",
  taskEfficiency:"Hiệu quả tác vụ", taskEfficiencySubtitle:"Thời gian hoàn thành trung vị của các luồng quan trọng.", deviceMix:"Thiết bị", deviceMixSubtitle:"Nơi tập trung nhiều friction UX.", mobile:"Điện thoại", desktop:"Desktop", tablet:"Tablet",
  uxPriorities:"Ưu tiên UX", uxPrioritySubtitle:"Tác động × bằng chứng × độ tin cậy.", high:"CAO", medium:"TRUNG BÌNH", mobileCheckout:"Friction ở checkout mobile", pricingHesitation:"Người dùng do dự khi so sánh giá", investigate:"Điều tra", viewHeatmap:"Xem heatmap",
  pageAttention:"Xếp hạng mức độ chú ý theo trang", pageAttentionSubtitle:"Ưu tiên dựa trên attention, exit và friction.", views:"Lượt xem", dwell:"Thời gian hiện diện", exit:"Thoát", activeTimeShort:"Active time", attentionFilter:"Active time",
  analyticsTitle:"Phân tích dữ liệu", analyticsSubtitle:"Traffic, attention và hiệu quả trong một màn hình.", allDevices:"Tất cả thiết bị", activeUsersAttention:"Người dùng hoạt động & attention", activeUsersAttentionSubtitle:"Người dùng hoạt động và mức chú ý theo ngày.", attentionMix:"Phân bổ attention", attentionMixSubtitle:"Các trang đang chiếm nhiều active time.", pageViews:"Lượt xem trang", avgDwell:"Dwell time TB", exitRate:"Tỷ lệ thoát",
  heatmapsTitle:"Heatmaps", heatmapsSubtitle:"Click, scroll và attention theo từng khu vực của trang.", attention:"Attention", clicks:"Click", scroll:"Scroll", rageClicks:"Rage click", deadClicks:"Dead click", attentionHeatmap:"Heatmap attention", attentionHeatmapSubtitle:"Vùng nóng cho biết người dùng dành nhiều active time hơn.", sectionAttention:"Attention theo section", sectionAttentionSubtitle:"Xếp hạng theo active time.", designSignal:"Tín hiệu thiết kế", designSignalText:"Feature comparison nhận lượng attention cao gấp 4 lần CTA chính.", rageClickLabel:"Rage click", deadClickLabel:"Dead click", scrollDepth:"Độ sâu scroll", paymentCta:"CTA thanh toán", planCards:"Card gói dịch vụ", pricingPage:"Trang pricing",
  sessionsTitle:"Phiên truy cập", sessionsSubtitle:"Kết nối hành trình người dùng với friction và kết quả tác vụ.", filterSessions:"Lọc phiên", sessionExplorer:"Khám phá phiên", sessionExplorerSubtitle:"Chọn một phiên để kiểm tra hành trình.", session:"Phiên", device:"Thiết bị", location:"Vị trí", duration:"Thời lượng", lastStep:"Bước cuối", signal:"Tín hiệu", healthy:"Ổn định", replay:"Replay", replaySubtitle:"Mobile · Việt Nam · 4 phút 32 giây", playReplay:"Phát replay", friction:"FRICTION", paymentHesitation:"Do dự ở bước thanh toán", paymentHesitationText:"1 phút 28 giây ở Payment, quay lại 2 lần và click lặp trước khi thoát.",
  tasksTitle:"Hiệu quả tác vụ", tasksSubtitle:"Đo tốc độ, tỷ lệ thành công, backtracking và lỗi của các luồng quan trọng.", checkout:"Checkout", signup:"Đăng ký", contact:"Liên hệ", medianCompletion:"Thời gian hoàn thành TB", backtracking:"Backtracking", errorRate:"Tỷ lệ lỗi", timePerStep:"Thời gian theo từng bước", timePerStepSubtitle:"Payment đang chiếm phần lớn thời gian.", seconds:"Giây", stepSuccess:"Tỷ lệ thành công theo bước", stepSuccessSubtitle:"Xác định nơi người dùng không thể tiếp tục.", paymentSlow:"Bước Payment chậm hơn 2,8×", paymentSlowText:"63% tổng thời gian tác vụ nằm ở bước này. Hãy kiểm tra replay và heatmap trước khi redesign.",
  feedbackTitle:"Phản hồi", feedbackSubtitle:"Kết hợp khảo sát với bối cảnh hành vi thực tế.", createSurvey:"Tạo khảo sát", csat:"CSAT", nps:"NPS", ces:"CES", recentFeedback:"Phản hồi gần đây", recentFeedbackSubtitle:"Phản hồi gắn với trang và hành trình.", negative:"Tiêu cực", positive:"Tích cực", neutral:"Trung tính", negativeConcentration:"Tập trung phản hồi tiêu cực", negativeConcentrationSubtitle:"Những nơi có friction về mặt định tính.",
  funnelsTitle:"Phễu chuyển đổi", funnelsSubtitle:"Xác định nơi các luồng quan trọng mất đà.", createFunnel:"+ Tạo funnel", checkoutConversion:"Phễu checkout", checkoutConversionSubtitle:"10.000 người dùng bắt đầu luồng này.", dropOff:"Drop-off", dropOffSubtitle:"Tỷ lệ chuyển đổi giữa các bước.", bottleneck:"ĐIỂM NGHẼN", productContact:"Product → Contact", productContactText:"82% người dùng biến mất trước Contact. Hãy kiểm tra attention ở pricing và độ rõ của CTA.",
  aiTitle:"AI Analyst", aiSubtitle:"Biến tín hiệu hành vi thành quyết định UX có ưu tiên và có bằng chứng.", runAudit:"Chạy UX audit", topPriorities:"Ưu tiên UX", topPrioritiesSubtitle:"Xếp hạng theo tác động × bằng chứng × độ tin cậy.", confidence:"ĐỘ TIN CẬY", recommendedAction:"Đề xuất hành động", inspectSessions:"Kiểm tra session", inspectHeatmap:"Kiểm tra heatmap", evidenceChain:"Chuỗi bằng chứng", evidenceChainSubtitle:"Truy ngược mọi đề xuất về hành vi quan sát được.", page:"Trang", section:"Section", task:"Tác vụ",
  pricing:"Pricing", productDetail:"Chi tiết sản phẩm", homepage:"Trang chủ", checkoutPage:"Checkout", contactPage:"Liên hệ", featureComparison:"So sánh tính năng", planComparison:"So sánh gói", faq:"FAQ", primaryCta:"CTA chính", payment:"Payment", shipping:"Shipping", cart:"Cart", success:"Success",
  electronic:"Điện tử", electronicSub:"Điện thoại, Earbuds, TV", fashion:"Thời trang", fashionSub:"Áo, Jeans, Giày", decor:"Trang trí", decorSub:"Nghệ thuật, Dining", sports:"Thể thao", sportsSub:"Bóng đá, Cricket", vietnam:"Việt Nam", singapore:"Singapore", iphone:"Mobile · iPhone", chrome:"Desktop · Chrome", android:"Mobile · Android", safari:"Desktop · Safari", healthySignal:"Ổn định",
  sandboxTitle:"Tracking Sandbox", sandboxSubtitle:"Gửi event có kiểm soát qua backend Datatalk thật mà không cần tạo project khách hàng.", liveData:"Dữ liệu sandbox live", demoData:"Dữ liệu mẫu", eventCount:"Sự kiện", sessionCount:"Phiên", activeTimeSandbox:"Active time", sectionAttentionSandbox:"Section attention", taskSuccessSandbox:"Task success", seedScenario:"Tạo scenario thực tế", resetSandbox:"Reset sandbox", sessionControls:"Phiên", interactionControls:"Tương tác", attentionControls:"Attention", taskControls:"Tác vụ", feedbackControls:"Phản hồi", startSession:"Bắt đầu phiên", endSession:"Kết thúc phiên", pageView:"Page view", sectionView:"Section view", heartbeat30:"Heartbeat +30s", clickEvent:"Click", rageClickEvent:"Rage click", deadClickEvent:"Dead click", scroll72:"Scroll 72%", taskStart:"Bắt đầu task", taskStep:"Task step", taskError:"Task error", taskBacktrack:"Backtrack", taskComplete:"Hoàn thành task", sendFeedback:"Gửi phản hồi", clearLog:"Xóa log", eventLog:"Event log", noEvents:"Chưa có event live. Hãy bắt đầu phiên hoặc tạo scenario.", backendStatus:"Kết nối backend", backendLive:"Backend v1.3.5 · live", trialProject:"Trial sandbox nội bộ", topPage:"Trang nổi bật", topSection:"Section nổi bật", openSandbox:"Mở sandbox"
};

Object.assign(en, {
  projectsTitle:"Projects", product:"Product", settings:"Settings", help:"Help & support", exitTrial:"Exit trial", trialWorkspace:"Trial workspace",
  trackingActive:"Tracking active", lastSync:"Synced just now", yourProducts:"Your products", projectsSubtitle:"Manage connected experiences and see tracking health at a glance.", addProject:"Add project",
  setupProgress:"Setup progress", visitors:"Visitors", lastEvent:"Last event", openAnalytics:"Open analytics", connected:"Connected",
  projectSetup:"PROJECT SETUP", createNewProject:"Create a new project", createProjectSubtitle:"Tell Datatalk what you want to understand. We’ll guide you through tracking setup next.",
  choosePlatform:"Platform", projectDetails:"Project details", installTracking:"Install", easySetup:"Designed for non-technical teams", easySetupText:"Choose your product type and Datatalk will generate the right installation guide for you.",
  noCodeRequired:"No coding required for guided options", guidedInstallation:"Step-by-step installation", verifyBeforeFinish:"Connection check before you finish", needHelp:"Need help?", setupAssistant:"Setup assistant will guide you",
  whatTrack:"What do you want to track?", whatTrackSubtitle:"Choose the experience your users interact with.", website:"Website", webApp:"Web App", mobileApp:"Mobile App", figmaSite:"Figma Site",
  websiteDesc:"Landing pages, ecommerce, blogs", webAppDesc:"SaaS products and dashboards", mobileAppDesc:"iOS and Android experiences", figmaSiteDesc:"Published Figma Sites and prototypes",
  continue:"Continue", projectDetailsSubtitle:"Give your project a clear name and goal. You can change these later.", projectName:"Project name", projectNameHint:"Use a name your team will recognize.", websiteUrl:"Website or product URL", websiteUrlHint:"Used to match incoming tracking events.",
  businessGoal:"Primary goal", goalUx:"UX improvement", goalConversion:"Conversion", goalResearch:"Product research", goalRetention:"Retention", platform:"Platform", back:"Back", createProject:"Create project", creatingProject:"Creating project…", couldNotCreateProject:"Could not create project", 
  ofSessions:"of sessions", baseline:"Baseline", openSandbox:"Open sandbox", lastEventMinutes:"2 minutes ago"
});
Object.assign(vi, {
  projectsTitle:"Dự án", product:"Sản phẩm", settings:"Cài đặt", help:"Trợ giúp", exitTrial:"Thoát bản dùng thử", trialWorkspace:"Workspace dùng thử",
  trackingActive:"Đang theo dõi", lastSync:"Vừa đồng bộ", yourProducts:"Sản phẩm của bạn", projectsSubtitle:"Quản lý các trải nghiệm đã kết nối và theo dõi tình trạng tracking trong một màn hình.", addProject:"Thêm dự án",
  setupProgress:"Tiến độ cài đặt", visitors:"Người dùng", lastEvent:"Event gần nhất", openAnalytics:"Mở phân tích", connected:"Đã kết nối",
  projectSetup:"THIẾT LẬP DỰ ÁN", createNewProject:"Tạo dự án mới", createProjectSubtitle:"Cho Datatalk biết bạn muốn phân tích gì. Hệ thống sẽ hướng dẫn cài tracking ở bước tiếp theo.",
  choosePlatform:"Nền tảng", projectDetails:"Thông tin dự án", installTracking:"Cài tracking", easySetup:"Thiết kế cho cả người không biết lập trình", easySetupText:"Chọn loại sản phẩm và Datatalk sẽ tạo hướng dẫn cài đặt phù hợp cho bạn.",
  noCodeRequired:"Có lựa chọn không cần viết code", guidedInstallation:"Hướng dẫn từng bước", verifyBeforeFinish:"Kiểm tra kết nối trước khi hoàn tất", needHelp:"Cần hỗ trợ?", setupAssistant:"Trợ lý thiết lập sẽ hướng dẫn bạn",
  whatTrack:"Bạn muốn theo dõi sản phẩm nào?", whatTrackSubtitle:"Chọn loại trải nghiệm mà người dùng đang tương tác.", website:"Website", webApp:"Web App", mobileApp:"Ứng dụng di động", figmaSite:"Figma Site",
  websiteDesc:"Landing page, ecommerce, blog", webAppDesc:"SaaS, dashboard và web app", mobileAppDesc:"Trải nghiệm iOS và Android", figmaSiteDesc:"Figma Site hoặc prototype đã publish",
  continue:"Tiếp tục", projectDetailsSubtitle:"Đặt tên rõ ràng và chọn mục tiêu chính. Bạn có thể thay đổi sau.", projectName:"Tên dự án", projectNameHint:"Dùng tên mà team của bạn dễ nhận biết.", websiteUrl:"URL website hoặc sản phẩm", websiteUrlHint:"Dùng để đối chiếu event tracking gửi về.",
  businessGoal:"Mục tiêu chính", goalUx:"Cải thiện UX", goalConversion:"Tăng chuyển đổi", goalResearch:"Nghiên cứu sản phẩm", goalRetention:"Giữ chân người dùng", platform:"Nền tảng", back:"Quay lại", createProject:"Tạo dự án", creatingProject:"Đang tạo dự án…", couldNotCreateProject:"Không thể tạo dự án",
  ofSessions:"trên tổng phiên", baseline:"Mốc so sánh", openSandbox:"Mở sandbox", lastEventMinutes:"2 phút trước"
});

const I18nContext=createContext<{lang:Lang;setLang:(l:Lang)=>void;t:(k:string)=>string}>({lang:"en",setLang:()=>{},t:k=>k});
export function I18nProvider({children}:{children:React.ReactNode}){const [lang,setLangState]=useState<Lang>("en");useEffect(()=>{const saved=localStorage.getItem("datatalk-lang") as Lang|null;if(saved) setLangState(saved)},[]);useEffect(()=>{localStorage.setItem("datatalk-lang",lang);document.documentElement.lang=lang},[lang]);const setLang=(l:Lang)=>setLangState(l);const dict=lang==="vi"?vi:en;const value=useMemo(()=>({lang,setLang,t:(k:string)=>dict[k]??en[k]??k}),[lang]);return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>}
export const useI18n=()=>useContext(I18nContext);
