// Datatalk Web SDK v1.3.1
(function(){
  var script=document.currentScript,key=script&&script.dataset&&script.dataset.project,api=(script&&script.dataset&&script.dataset.endpoint)||'';
  if(!key||!api)return;
  var makeId=function(prefix){try{return prefix+'_'+crypto.randomUUID()}catch(e){return prefix+'_'+Math.random().toString(36).slice(2)+Date.now()}};
  var storage=function(name,prefix){try{var value=localStorage.getItem(name);if(!value){value=makeId(prefix);localStorage.setItem(name,value)}return value}catch(e){return makeId(prefix)}};
  var visitor=storage('datatalk_visitor','visitor'),session=storage('datatalk_session','session');
  var visible=document.visibilityState==='visible',activeSince=Date.now(),pageEntered=Date.now(),currentPage=location.pathname;
  var sectionState={},taskState={},lastClick=0,rapid=0;
  var meta=function(){return {referrer:document.referrer,viewport_width:innerWidth,viewport_height:innerHeight,device:innerWidth<768?'mobile':innerWidth<1024?'tablet':'desktop'}};
  var send=function(event,extra){try{fetch(api+'/api/track/event',{method:'POST',keepalive:true,headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.assign({tracking_key:key,visitor_id:visitor,session_id:session,event:event,page:location.pathname},extra||{}))}).catch(function(){})}catch(e){}};
  var flush=function(type){if(!visible)return;var ms=Math.min(Date.now()-activeSince,30000);if(ms>0)send(type||'page_heartbeat',{metadata:Object.assign(meta(),{duration_ms:ms})});activeSince=Date.now()};
  var finishPage=function(){send('page_dwell',{metadata:Object.assign(meta(),{duration_ms:Math.min(Date.now()-pageEntered,300000)})});};
  var sectionObserver=new IntersectionObserver(function(entries){entries.forEach(function(entry){var el=entry.target,id=el.getAttribute('data-datatalk-section');if(!id)return;var state=sectionState[id]||{visible:false,started:0,total:0};if(entry.isIntersecting&&entry.intersectionRatio>=0.35&&!state.visible){state.visible=true;state.started=Date.now();sectionState[id]=state;send('section_view',{metadata:{section:id,visibility_ratio:entry.intersectionRatio}})}else if(!entry.isIntersecting&&state.visible){var d=Math.min(Date.now()-state.started,300000);state.visible=false;state.total+=d;sectionState[id]=state;send('section_exit',{metadata:{section:id,duration_ms:d,total_visible_ms:Math.min(state.total,900000)}})}})},{threshold:[0,0.35,0.6]});
  var observe=function(){document.querySelectorAll('[data-datatalk-section]').forEach(function(el){if(!el.__dtObserved){el.__dtObserved=true;sectionObserver.observe(el)}})};
  var sectionBeat=function(){Object.keys(sectionState).forEach(function(id){var s=sectionState[id];if(s.visible){var d=Math.min(Date.now()-s.started,30000);if(d>0){send('section_heartbeat',{metadata:{section:id,duration_ms:d}});s.started=Date.now()}}})};
  var route=function(){var next=location.pathname;if(next===currentPage)return;finishPage();Object.keys(sectionState).forEach(function(id){var s=sectionState[id];if(s.visible)send('section_exit',{metadata:{section:id,duration_ms:Math.min(Date.now()-s.started,300000)}})});sectionState={};currentPage=next;pageEntered=Date.now();activeSince=Date.now();send('page_view',{metadata:meta()});setTimeout(observe,0)};
  ['pushState','replaceState'].forEach(function(name){var original=history[name];history[name]=function(){var result=original.apply(this,arguments);route();return result}});addEventListener('popstate',route);
  send('session_start',{metadata:meta()});send('page_view',{metadata:meta()});setTimeout(observe,0);setInterval(function(){flush();sectionBeat()},10000);
  document.addEventListener('visibilitychange',function(){if(document.visibilityState==='hidden'){visible=false;flush('page_hidden')}else{visible=true;activeSince=Date.now();pageEntered=Date.now();send('page_visible',{metadata:meta()});setTimeout(observe,0)}});
  addEventListener('scroll',function(){clearTimeout(window.__dtScroll);window.__dtScroll=setTimeout(function(){var h=document.documentElement.scrollHeight-innerHeight,depth=h>0?Math.round(scrollY/h*100):100;send('scroll',{metadata:Object.assign(meta(),{depth:depth,scroll_y:scrollY})})},180)},{passive:true});
  document.addEventListener('click',function(e){var target=e.target&&e.target.closest?e.target.closest('a,button,input,select,textarea,[role=button]'):e.target;var section=target&&target.closest?target.closest('[data-datatalk-section]'):null;var metadata=Object.assign(meta(),{x:e.clientX,y:e.clientY,section:section&&section.getAttribute('data-datatalk-section')||null});var tag=String(target&&target.tagName||'UNKNOWN'),text=String(target&&target.innerText||target&&target.getAttribute&&target.getAttribute('aria-label')||'').slice(0,120);send('click',{element:tag,element_text:text,metadata:metadata});var t=Date.now();rapid=t-lastClick<700?rapid+1:1;lastClick=t;if(rapid>=3){send('rage_click',{element:tag,element_text:text,metadata:Object.assign(metadata,{clicks:rapid})});rapid=0}if(!target||!target.closest||!target.closest('a,button,input,select,textarea,[role=button]'))send('dead_click',{element:tag,element_text:text,metadata:metadata})},{passive:true});
  addEventListener('beforeunload',function(){finishPage();Object.keys(sectionState).forEach(function(id){var s=sectionState[id];if(s.visible)send('section_exit',{metadata:{section:id,duration_ms:Math.min(Date.now()-s.started,300000)}})});send('session_end',{metadata:Object.assign(meta(),{duration_ms:Math.min(Date.now()-pageEntered,300000)})})});
  window.DatatalK={track:function(name,data){send(name,{metadata:data||{}})},identify:function(id,data){visitor=id;send('identify',{visitor_id:id,metadata:data||{}})},taskStart:function(name,data){taskState[name]={started:Date.now()};send('task_start',{metadata:Object.assign({task:name},data||{})})},taskStep:function(name,step,data){var s=taskState[name]||{started:Date.now()},duration=Math.min(Date.now()-s.started,300000);s.started=Date.now();taskState[name]=s;send('task_step',{metadata:Object.assign({task:name,step:step,duration_ms:duration},data||{})})},taskError:function(name,step,data){send('task_error',{metadata:Object.assign({task:name,step:step},data||{})})},taskBacktrack:function(name,from,to,data){send('task_backtrack',{metadata:Object.assign({task:name,from:from,to:to},data||{})})},taskComplete:function(name,data){var s=taskState[name],duration=s?Math.min(Date.now()-s.started,300000):0;send('task_complete',{metadata:Object.assign({task:name,duration_ms:duration},data||{})});delete taskState[name]}};
})();
