export function buildSdk(apiBase) {
  return `(()=>{
const s=document.currentScript,key=s?.dataset?.project,API=${JSON.stringify(apiBase)};if(!key)return;
const id=(p)=>{try{return p+'_'+crypto.randomUUID()}catch{return p+'_'+Math.random().toString(36).slice(2)+Date.now()}};
const storage=(area,k,p)=>{try{let v=area.getItem(k);if(!v){v=id(p);area.setItem(k,v)}return v}catch{return id(p)}};
let visitor=storage(localStorage,'datatalk_visitor','visitor'),session=storage(sessionStorage,'datatalk_session','session');
let visible=document.visibilityState==='visible',pageEntered=Date.now(),activeSince=Date.now(),currentRoute=location.pathname+location.search+location.hash,sectionState=new Map(),taskState=new Map(),lastClick={key:'',at:0,count:0};
const browser=()=>{const ua=navigator.userAgent;if(/Edg\\//.test(ua))return'Edge';if(/Chrome\\//.test(ua))return'Chrome';if(/Safari\\//.test(ua)&&!/Chrome\\//.test(ua))return'Safari';if(/Firefox\\//.test(ua))return'Firefox';return'Other'};
const os=()=>{const ua=navigator.userAgent;if(/Windows/.test(ua))return'Windows';if(/Mac OS|Macintosh/.test(ua))return'macOS';if(/Android/.test(ua))return'Android';if(/iPhone|iPad|iOS/.test(ua))return'iOS';return'Other'};
const cleanPath=()=>location.pathname||'/';
const pageName=()=>{const manual=document.documentElement?.getAttribute('data-datatalk-page-name')||document.querySelector('meta[name=\"datatalk-page-name\"]')?.getAttribute('content')||document.querySelector('[data-datatalk-page-name]')?.getAttribute('data-datatalk-page-name');const h1=document.querySelector('h1')?.textContent?.trim();const title=document.title?.trim();return String(manual||h1||title||cleanPath()).slice(0,180)};
const pageMeta=()=>({page_path:cleanPath(),page_url:location.href,page_title:(document.title||'').trim()||null,page_name:pageName(),page_route_group:document.documentElement?.getAttribute('data-datatalk-route')||document.querySelector('meta[name=\"datatalk-route-group\"]')?.getAttribute('content')||null,referrer:document.referrer||null,viewport_width:innerWidth,viewport_height:innerHeight,screen_width:screen.width,screen_height:screen.height,document_width:Math.max(document.documentElement.scrollWidth,document.body?.scrollWidth||0),document_height:Math.max(document.documentElement.scrollHeight,document.body?.scrollHeight||0),device:innerWidth<768?'mobile':innerWidth<1024?'tablet':'desktop',browser:browser(),os:os(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||null,language:navigator.language||null});
const elementMeta=(target)=>{if(!target)return{};const label=String(target.innerText||target.getAttribute?.('aria-label')||target.getAttribute?.('title')||target.getAttribute?.('value')||'').trim().slice(0,160);const testid=target.getAttribute?.('data-testid')||target.getAttribute?.('data-test')||null;const elementId=target.id||null;const role=target.getAttribute?.('role')||null;const href=target.getAttribute?.('href')||null;const keyHint=testid?('testid:'+testid):elementId?('id:'+elementId):role&&label?('role:'+role+':'+label):label?((target.tagName||'EL').toLowerCase()+':'+label):String(target.tagName||'UNKNOWN').toLowerCase();return{element_key:keyHint,element_id:elementId,element_testid:testid,element_role:role,element_label:label,href}};
const recordingToken=()=>{const q=new URLSearchParams(location.search).get('datatalk_record_funnel');if(q){try{sessionStorage.setItem('datatalk_record_funnel',q)}catch{}}try{return q||sessionStorage.getItem('datatalk_record_funnel')}catch{return q}};
const send=(event,extra={})=>{const body={tracking_key:key,visitor_id:visitor,session_id:session,event,page:cleanPath(),...extra,metadata:{...pageMeta(),...(extra.metadata||{})}};const token=recordingToken();if(token)body.metadata.funnel_recording_token=token;try{fetch(API+'/api/track/event',{method:'POST',keepalive:true,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}).catch(()=>{})}catch{}};
const flushPage=(type='page_heartbeat')=>{if(!visible)return;const d=Math.min(Date.now()-activeSince,30000);if(d>0)send(type,{metadata:{duration_ms:d}});activeSince=Date.now()};
const closePage=()=>{const dwell=Math.min(Date.now()-pageEntered,300000);send('page_dwell',{metadata:{duration_ms:dwell}});activeSince=Date.now();pageEntered=Date.now()};
const observe=()=>{if(!('IntersectionObserver'in window))return;document.querySelectorAll('[data-datatalk-section]').forEach(el=>{if(el.__dtObserved)return;el.__dtObserved=true;sectionObserver.observe(el)})};
const sectionObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{const el=entry.target,section=el.getAttribute('data-datatalk-section');if(!section)return;const st=sectionState.get(section)||{visible:false,started:0,total:0};if(entry.isIntersecting&&entry.intersectionRatio>=.35&&!st.visible){st.visible=true;st.started=Date.now();sectionState.set(section,st);send('section_view',{metadata:{section,visibility_ratio:entry.intersectionRatio}})}else if(!entry.isIntersecting&&st.visible){const d=Math.min(Date.now()-st.started,300000);st.visible=false;st.total+=d;sectionState.set(section,st);send('section_exit',{metadata:{section,duration_ms:d,total_visible_ms:Math.min(st.total,900000)}})}}),{threshold:[0,.35,.6]});
const sectionHeartbeat=()=>sectionState.forEach((st,section)=>{if(st.visible){const d=Math.min(Date.now()-st.started,30000);if(d>0){send('section_heartbeat',{metadata:{section,duration_ms:d}});st.started=Date.now()}}});
const route=()=>{const next=location.pathname+location.search+location.hash;if(next===currentRoute)return;closePage();sectionState.forEach((st,section)=>{if(st.visible)send('section_exit',{metadata:{section,duration_ms:Math.min(Date.now()-st.started,300000)}})});sectionState=new Map();currentRoute=next;setTimeout(()=>{send('page_view');observe()},60)};
const wrap=(name)=>{const original=history[name];history[name]=function(){const r=original.apply(this,arguments);queueMicrotask(route);return r}};wrap('pushState');wrap('replaceState');addEventListener('popstate',route);addEventListener('hashchange',route);
send('session_start');send('page_view');setTimeout(observe,0);setInterval(()=>{flushPage();sectionHeartbeat()},10000);
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){flushPage('page_hidden');visible=false}else{visible=true;activeSince=Date.now();pageEntered=Date.now();send('page_visible');setTimeout(observe,0)}});
addEventListener('scroll',()=>{clearTimeout(window.__dtScroll);window.__dtScroll=setTimeout(()=>{const h=document.documentElement.scrollHeight-innerHeight,depth=h>0?Math.round(scrollY/h*100):100;send('scroll',{metadata:{depth,scroll_y:scrollY}})},180)},{passive:true});
document.addEventListener('click',e=>{const interactive=e.target?.closest?.('a,button,input,select,textarea,[role=button],[data-datatalk-click]');const target=interactive||e.target;const em=elementMeta(target);const section=target?.closest?.('[data-datatalk-section]')?.getAttribute('data-datatalk-section')||null;const rect=target?.getBoundingClientRect?.();const meta={...em,x:e.clientX,y:e.clientY,document_x:e.clientX+scrollX,document_y:e.clientY+scrollY,document_width:Math.max(document.documentElement.scrollWidth,document.body?.scrollWidth||0),document_height:Math.max(document.documentElement.scrollHeight,document.body?.scrollHeight||0),element_x:rect?rect.left+scrollX:null,element_y:rect?rect.top+scrollY:null,element_width:rect?rect.width:null,element_height:rect?rect.height:null,section};send('click',{element:String(target?.tagName||'UNKNOWN'),element_text:em.element_label||'',metadata:meta});const now=Date.now(),same=lastClick.key===em.element_key&&now-lastClick.at<700;lastClick={key:em.element_key,at:now,count:same?lastClick.count+1:1};if(lastClick.count>=3){send('rage_click',{element:String(target?.tagName||'UNKNOWN'),element_text:em.element_label||'',metadata:{...meta,clicks:lastClick.count}});lastClick.count=0}if(!interactive&&String(target?.tagName||'').toLowerCase()!=='body')send('dead_click',{element:String(target?.tagName||'UNKNOWN'),element_text:em.element_label||'',metadata:meta})},{passive:true});
addEventListener('beforeunload',()=>{flushPage('page_dwell');send('session_end',{metadata:{duration_ms:Math.min(Date.now()-pageEntered,300000)}})});
const submitFeedback=(survey,score,feedback)=>{fetch(API+'/api/track/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tracking_key:key,session_id:session,page:cleanPath(),survey_type:survey.survey_type,score:score??null,feedback:String(feedback||'').slice(0,4000),metadata:{...pageMeta(),survey_id:survey.id,page_url:location.href,page_title:document.title}})}).catch(()=>{});send('feedback_submit',{metadata:{survey_id:survey.id,score:score??null,feedback_type:survey.survey_type}})};
const surveyBox=(survey)=>{if(!survey||document.getElementById('datatalk-survey'))return;const box=document.createElement('div');box.id='datatalk-survey';box.style.cssText='position:fixed;right:20px;bottom:20px;z-index:2147483647;width:min(380px,calc(100vw - 40px));background:#fff;color:#20222a;border:1px solid #e6e8ef;border-radius:14px;box-shadow:0 18px 50px rgba(30,32,48,.18);padding:18px;font:14px/1.45 system-ui,sans-serif';const title=document.createElement('div');title.style.cssText='font-weight:700;font-size:15px;margin:0 26px 12px 0';title.textContent=survey.question;box.appendChild(title);const finish=(score,feedback)=>{submitFeedback(survey,score,feedback);box.remove()};const type=survey.survey_type||'rating';if(type==='text'){const ta=document.createElement('textarea');ta.placeholder=survey.placeholder||'Share your feedback';ta.style.cssText='width:100%;min-height:88px;box-sizing:border-box;border:1px solid #dfe2ea;border-radius:9px;padding:9px;resize:vertical';box.appendChild(ta);const b=document.createElement('button');b.textContent='Send';b.style.cssText='margin-top:10px;border:0;background:#696cff;color:#fff;border-radius:8px;padding:8px 14px;cursor:pointer';b.onclick=()=>finish(null,ta.value||'text');box.appendChild(b)}else if(type==='yes_no'){const row=document.createElement('div');row.style.cssText='display:flex;gap:8px';['Yes','No'].forEach((label,i)=>{const b=document.createElement('button');b.textContent=label;b.style.cssText='flex:1;border:1px solid #dfe2ea;background:#fff;border-radius:8px;padding:8px;cursor:pointer';b.onclick=()=>finish(i===0?1:0,label.toLowerCase());row.appendChild(b)});box.appendChild(row)}else if(type==='multiple_choice'){const options=Array.isArray(survey.options)?survey.options:[];const row=document.createElement('div');row.style.cssText='display:grid;gap:7px';options.forEach((label,i)=>{const b=document.createElement('button');b.textContent=String(label);b.style.cssText='text-align:left;border:1px solid #dfe2ea;background:#fff;border-radius:8px;padding:8px 10px;cursor:pointer';b.onclick=()=>finish(i,String(label));row.appendChild(b)});box.appendChild(row)}else{const scale=document.createElement('div');scale.style.cssText='display:flex;gap:6px;flex-wrap:wrap';const min=Number(survey.scale_min??(type==='nps'?0:1)),max=Number(survey.scale_max??(type==='nps'?10:type==='ces'?7:5));for(let i=min;i<=max;i++){const b=document.createElement('button');b.textContent=String(i);b.style.cssText='border:1px solid #dfe2ea;background:#fff;border-radius:8px;padding:7px 10px;cursor:pointer';b.onclick=()=>finish(i,'rating');scale.appendChild(b)}box.appendChild(scale)}const close=document.createElement('button');close.textContent='×';close.setAttribute('aria-label','Close');close.style.cssText='position:absolute;right:10px;top:8px;border:0;background:transparent;font-size:20px;cursor:pointer';close.onclick=()=>box.remove();box.appendChild(close);document.body.appendChild(box)};
const showRecorder=()=>{const token=recordingToken();if(!token||document.getElementById('datatalk-recorder'))return;const bar=document.createElement('div');bar.id='datatalk-recorder';bar.style.cssText='position:fixed;left:50%;top:12px;transform:translateX(-50%);z-index:2147483647;background:#20222a;color:#fff;border-radius:999px;padding:8px 14px;box-shadow:0 10px 28px rgba(0,0,0,.2);font:600 12px system-ui,sans-serif';bar.textContent='● DataTalk · Recording funnel flow';document.body.appendChild(bar)};
setTimeout(()=>{showRecorder();fetch(API+'/api/track/surveys?tracking_key='+encodeURIComponent(key)+'&page='+encodeURIComponent(cleanPath())).then(r=>r.ok?r.json():null).then(d=>{const survey=d?.surveys?.[0];if(survey)setTimeout(()=>surveyBox(survey),Math.max(0,Number(survey.delay_ms||0))) }).catch(()=>{})},1200);
window.DatatalK={track:(name,data={})=>send(name,{metadata:data}),identify:(visitorId,data={})=>{visitor=visitorId;send('identify',{visitor_id:visitorId,metadata:data})},taskStart:(name,data={})=>{taskState.set(name,{started:Date.now()});send('task_start',{metadata:{task:name,...data}})},taskStep:(name,step,data={})=>{const st=taskState.get(name)||{started:Date.now()};const duration=Math.min(Date.now()-st.started,300000);st.started=Date.now();taskState.set(name,st);send('task_step',{metadata:{task:name,step,duration_ms:duration,...data}})},taskError:(name,step,data={})=>send('task_error',{metadata:{task:name,step,...data}}),taskBacktrack:(name,from,to,data={})=>send('task_backtrack',{metadata:{task:name,from,to,...data}}),taskComplete:(name,data={})=>{const st=taskState.get(name);send('task_complete',{metadata:{task:name,duration_ms:st?Math.min(Date.now()-st.started,300000):0,...data}});taskState.delete(name)},taskFail:(name,step,data={})=>{send('task_fail',{metadata:{task:name,step,...data}});taskState.delete(name)},taskAbandon:(name,step,data={})=>{send('task_abandon',{metadata:{task:name,step,...data}});taskState.delete(name)}};
})();`;
}
