'use client';
import { useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Chrome, Eye, EyeOff, Sparkles } from 'lucide-react';
import { supabase } from '@/lib/supabase';
export default function Register(){ const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [show,setShow]=useState(false); const [error,setError]=useState(''); const [done,setDone]=useState(false); const [busy,setBusy]=useState(false);
 async function create(){setError('');setBusy(true);if(!supabase){setError('Supabase is not configured.');setBusy(false);return;} const {error}=await supabase.auth.signUp({email:email.trim(),password,options:{data:{name},emailRedirectTo:`${window.location.origin}/auth/callback`}});setBusy(false);if(error)setError(error.message);else setDone(true);}
 async function google(){if(!supabase){setError('Supabase is not configured.');return;}setBusy(true);const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:`${window.location.origin}/auth/callback`}});if(error){setBusy(false);setError(error.message);}}
 return <main className="auth-page"><div className="auth-card"><div className="auth-brand"><div className="brand-mark"><Sparkles size={16}/></div><span>datatalk</span></div><div className="auth-copy"><span className="eyebrow">CREATE ACCOUNT</span><h1>Start with your first product.</h1><p>Connect a website or app and let DataTalk turn behavior into UX decisions.</p></div><button className="google-button" onClick={google} disabled={busy}><Chrome size={17}/> Continue with Google</button><div className="or"><span>or create with email</span></div><label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name" autoComplete="name"/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com" autoComplete="email" required/></label><label>Password<div className="password-field"><input type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 12 characters" minLength={12} autoComplete="new-password" required/><button type="button" className="password-toggle" onClick={()=>setShow(v=>!v)} aria-label={show?'Hide password':'Show password'}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label>{error&&<div className="auth-error">{error}</div>}{done&&<div className="success-box auth-success"><strong>Check your email</strong><span>Confirm your account, then sign in to DataTalk.</span></div>}<button className="primary-button auth-submit" onClick={create} disabled={busy||done}>{busy?'Creating account…':'Create account'}<ArrowRight size={15}/></button><p className="auth-switch">Already have an account? <Link href="/login">Sign in</Link></p></div></main>}
