'use client';
import { useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Chrome, Sparkles } from 'lucide-react';
import { supabase } from '../../lib/supabase';
export default function Register(){ const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [done,setDone]=useState(false);
 async function create(){setError('');if(!supabase){setError('Supabase is not configured.');return;} const {error}=await supabase.auth.signUp({email,password,options:{data:{name},emailRedirectTo:`${window.location.origin}/auth/callback`}});if(error)setError(error.message);else setDone(true);}
 async function google(){if(!supabase){setError('Supabase is not configured.');return;} const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:`${window.location.origin}/auth/callback`}});if(error)setError(error.message);}
 return <main className="auth-page"><div className="auth-card"><div className="auth-brand"><div className="brand-mark"><Sparkles size={16}/></div><span>datatalk</span></div><div className="auth-copy"><span className="eyebrow">CREATE ACCOUNT</span><h1>Start with your first product.</h1><p>Connect a website or app and let Datatalk turn behavior into UX decisions.</p></div><button className="google-button" onClick={google}><Chrome size={17}/> Continue with Google</button><div className="or"><span>or create with email</span></div><label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 8 characters"/></label>{error&&<div className="auth-error">{error}</div>}{done&&<div className="success-box auth-success"><strong>Check your email</strong><span>Confirm your account, then sign in to Datatalk.</span></div>}<button className="primary-button auth-submit" onClick={create}>Create account <ArrowRight size={15}/></button><p className="auth-switch">Already have an account? <Link href="/login">Sign in</Link></p></div></main>}
