'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Plus } from 'lucide-react';
import { LiveBoundary, useLiveResource } from '@/components/v2/LiveData';
import AnalyticsFilters, { toIsoDate, type AnalyticsFilterValue } from '@/components/AnalyticsFilters';
import { useProjects } from '@/components/ProjectProvider';
import { useI18n } from '@/components/i18n';
import { api } from '@/lib/api';

type Feedback={id:string;page:string;score:number|null;feedback:string;survey_type:string;created_at:string;metadata?:Record<string,unknown>};
type Data={responses:number;summary:{type:string;responses:number;averageScore:number|null;pages:Record<string,number>}[];feedback:Feedback[]};
type Survey={id:string;name:string;survey_type:string;question:string;page_path:string|null;status:string;delay_ms:number;scale_min:number|null;scale_max:number|null;options?:string[];placeholder?:string|null};
const initial:AnalyticsFilterValue={from:'',to:'',compare:'previous',page:'',device:''};
export default function FeedbackPage(){
 const {lang,t}=useI18n();const vi=lang==='vi';const {project}=useProjects();const [filter,setFilter]=useState(initial);const [surveys,setSurveys]=useState<Survey[]>([]);const [show,setShow]=useState(false);const [busy,setBusy]=useState(false);const [surveyType,setSurveyType]=useState('csat');
 const query=useMemo(()=>{const q=new URLSearchParams();const f=toIsoDate(filter.from),to=toIsoDate(filter.to);if(f)q.set('from',f);if(to)q.set('to',to);if(filter.page)q.set('page',filter.page);if(filter.device)q.set('device',filter.device);return q.toString()},[filter]);
 const resource=useLiveResource<Data>('feedback-v2',query);
 const load=()=>project&&api<Survey[]>(`/api/projects/${project.id}/surveys`).then(setSurveys).catch(()=>{});useEffect(()=>{load()},[project?.id]);
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!project)return;const fd=new FormData(e.currentTarget);const type=String(fd.get('type')||'csat');const options=String(fd.get('options')||'').split('\n').map(x=>x.trim()).filter(Boolean);setBusy(true);try{await api(`/api/projects/${project.id}/surveys`,{method:'POST',body:JSON.stringify({name:fd.get('name'),survey_type:type,question:fd.get('question'),page_path:fd.get('page')||null,delay_ms:Number(fd.get('delay')||0)*1000,scale_min:type==='nps'?0:1,scale_max:type==='nps'?10:type==='ces'?7:5,options,placeholder:fd.get('placeholder')||null,status:'ACTIVE'})});setShow(false);load()}finally{setBusy(false)}};
 const label=(type:string)=>type==='csat'?(vi?'Mức độ hài lòng khách hàng (CSAT)':'Customer satisfaction (CSAT)'):type==='nps'?(vi?'Khả năng giới thiệu sản phẩm (NPS)':'Net promoter score (NPS)'):type==='ces'?(vi?'Mức độ dễ dàng khi hoàn thành tác vụ (CES)':'Customer effort score (CES)'):type==='yes_no'?(vi?'Câu hỏi Có / Không':'Yes / No'):type==='multiple_choice'?(vi?'Lựa chọn nhiều phương án':'Multiple choice'):type==='text'?(vi?'Phản hồi văn bản':'Open text'):(vi?'Đánh giá 1–5':'Rating 1–5');
 const pageOptions=[...new Map((resource.data?.feedback||[]).map(f=>[f.page,{pagePath:f.page,pageName:f.page}])).values()];
 return <LiveBoundary title={t('feedback')} {...resource} subtitle={vi?'Khảo sát thật trên website và dữ liệu phản hồi gắn với trang/session.':'Real on-site surveys with page and session context.'} actions={<button className="btn primary" onClick={()=>setShow(true)}><Plus size={16}/>{vi?'Tạo khảo sát':'Create survey'}</button>}>
  <AnalyticsFilters value={filter} onChange={setFilter} pages={pageOptions}/>
  <div className="feedback-stat-grid">{['csat','nps','ces'].map(type=>{const row=resource.data?.summary.find(x=>x.type===type);return <div className="card feedback-stat" key={type}><span>{label(type)}</span><strong>{row?.averageScore==null?'--':row.averageScore}</strong><small>{row?.responses||0} {vi?'lượt đánh giá':'responses'}</small></div>})}<div className="card feedback-stat"><span>{vi?'Tổng phản hồi':'Total responses'}</span><strong>{resource.data?.responses??'--'}</strong></div></div>
  <section className="card account-panel"><div className="card-header"><div><h2>{vi?'Khảo sát đang cấy trên website':'Published surveys'}</h2><p>{vi?'SDK tự hiển thị popup theo trang và thời gian delay đã cấu hình.':'SDK renders the popup by page and delay settings.'}</p></div></div><div className="account-table-wrap"><table className="account-table"><thead><tr><th>{vi?'Tên':'Name'}</th><th>{vi?'Loại đánh giá':'Feedback type'}</th><th>{vi?'Câu hỏi':'Question'}</th><th>{vi?'Trang':'Page'}</th><th>{vi?'Trạng thái':'Status'}</th></tr></thead><tbody>{surveys.map(s=><tr key={s.id}><td>{s.name}</td><td>{label(s.survey_type)}</td><td>{s.question}</td><td>{s.page_path||(vi?'Tất cả trang':'All pages')}</td><td>{s.status}</td></tr>)}</tbody></table></div></section>
  <section className="card account-panel"><h2>{vi?'Phản hồi gần đây':'Recent feedback'}</h2><div className="account-table-wrap"><table className="account-table"><thead><tr><th>{vi?'Đánh giá về':'Feedback about'}</th><th>{vi?'Trang':'Page'}</th><th>{vi?'Điểm':'Score'}</th><th>{vi?'Nội dung':'Feedback'}</th><th>{vi?'Thời gian':'Time'}</th></tr></thead><tbody>{(resource.data?.feedback||[]).map(f=><tr key={f.id}><td>{label(f.survey_type)}</td><td>{f.page||'--'}</td><td>{f.score??'--'}</td><td>{f.feedback}</td><td>{new Date(f.created_at).toLocaleString(vi?'vi-VN':'en-US')}</td></tr>)}</tbody></table></div></section>
  {show&&<div className="modal-backdrop"><form className="card survey-modal" onSubmit={submit}><h2>{vi?'Tạo khảo sát website':'Create website survey'}</h2><label>{vi?'Tên khảo sát':'Survey name'}<input name="name" required placeholder={vi?'Ví dụ: Đánh giá Checkout':'e.g. Checkout feedback'}/></label><label>{vi?'Loại đánh giá':'Survey type'}<select name="type" value={surveyType} onChange={e=>setSurveyType(e.target.value)}><option value="csat">{label('csat')}</option><option value="nps">{label('nps')}</option><option value="ces">{label('ces')}</option><option value="rating">{label('rating')}</option><option value="yes_no">{label('yes_no')}</option><option value="multiple_choice">{label('multiple_choice')}</option><option value="text">{label('text')}</option></select></label><label>{vi?'Câu hỏi':'Question'}<textarea name="question" required placeholder={vi?'Bạn hài lòng với trải nghiệm này ở mức nào?':'How satisfied are you with this experience?'}/></label>{surveyType==='multiple_choice'&&<label>{vi?'Các lựa chọn (mỗi dòng một lựa chọn)':'Options (one per line)'}<textarea name="options" required placeholder={vi?'Rất dễ\nBình thường\nKhó':'Very easy\nNeutral\nDifficult'}/></label>}{surveyType==='text'&&<label>{vi?'Placeholder ô phản hồi':'Feedback placeholder'}<input name="placeholder" placeholder={vi?'Chia sẻ trải nghiệm của bạn…':'Share your experience…'}/></label>}<label>{vi?'Chỉ hiển thị ở path (để trống = tất cả)':'Page path (blank = all pages)'}<input name="page" placeholder="/checkout"/></label><label>{vi?'Hiển thị sau (giây)':'Show after (seconds)'}<input name="delay" inputMode="numeric" defaultValue="3"/></label><div className="account-actions"><button type="button" className="btn outline" onClick={()=>setShow(false)}>{vi?'Hủy':'Cancel'}</button><button className="btn primary" disabled={busy}>{busy?(vi?'Đang tạo…':'Creating…'):(vi?'Xuất bản khảo sát':'Publish survey')}</button></div></form></div>}
 </LiveBoundary>;
}
