'use client';
import Link from 'next/link';
import {Area,AreaChart,ResponsiveContainer,Tooltip,XAxis,YAxis,CartesianGrid} from 'recharts';
import {ArrowUpRight,CalendarDays,ChevronDown,Sparkles,MousePointer2,Users,Clock3,Target,Globe2,Smartphone} from 'lucide-react';
import {demoTraffic,demoInsights} from '@/lib/demo-data';

const cards=[['Visitors','8,421','+18.4%',Users],['Sessions','10,380','+12.8%',MousePointer2],['Avg. session','02:14','+8.2%',Clock3],['Conversions','742','+16.6%',Target]] as const;
export default function TrialOverview(){return <div>
 <header className="page-head"><div><div className="eyebrow">TRIAL EXPERIENCE</div><h1>Understand your product.</h1><p>See what users do, why they struggle, and what to improve next.</p></div><div className="head-actions"><button className="range"><CalendarDays size={16}/> Last 7 days <ChevronDown size={15}/></button><Link href="/try/projects" className="primary-btn">View project <ArrowUpRight size={16}/></Link></div></header>
 <section className="stat-grid">{cards.map(([label,value,delta,Icon])=><div className="stat-card" key={label}><div className="stat-top"><span>{label}</span><Icon size={17}/></div><strong>{value}</strong><div className="delta">{delta} <span>vs previous period</span></div></div>)}</section>
 <section className="content-grid wide-first"><div className="panel chart-panel"><div className="panel-head"><div><h2>Product traffic</h2><p>Visitors and sessions over time</p></div><button className="mini-select">Visitors <ChevronDown size={14}/></button></div><div className="chart"><ResponsiveContainer width="100%" height={285}><AreaChart data={demoTraffic}><defs><linearGradient id="fillVisitors" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#696cff" stopOpacity={.28}/><stop offset="100%" stopColor="#696cff" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#eceef2"/><XAxis dataKey="day" tick={{fontSize:12}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:12}} axisLine={false} tickLine={false}/><Tooltip/><Area type="monotone" dataKey="visitors" stroke="#696cff" fill="url(#fillVisitors)" strokeWidth={2}/><Area type="monotone" dataKey="sessions" stroke="#a4a8ff" fill="none" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></div>
 <div className="panel"><div className="panel-head"><div><h2>AI UX pulse</h2><p>What needs attention first</p></div><Sparkles size={19}/></div>{demoInsights.slice(0,3).map(i=><div className="insight-row" key={i.title}><div className={`severity ${i.severity.toLowerCase()}`}>{i.severity}</div><div><b>{i.title}</b><p>{i.text}</p></div><span>{i.impact}</span></div>)}</div></section>
 <section className="content-grid"><div className="panel"><div className="panel-head"><div><h2>Top pages</h2><p>Where users spend time</p></div><Link href="/try/analytics" className="text-link">View analytics</Link></div><div className="table"><div className="tr th"><span>Page</span><span>Views</span><span>Users</span><span>Exit</span></div>{[['/','8,240','4,920','28%'],['/products','5,620','3,610','34%'],['/about','2,180','1,690','41%'],['/contact','1,460','1,130','52%']].map(r=><div className="tr" key={r[0]}>{r.map((x,i)=><span key={i} className={i===0?'strong':''}>{x}</span>)}</div>)}</div></div>
 <div className="panel"><div className="panel-head"><div><h2>Audience snapshot</h2><p>Who is using your product</p></div><Globe2 size={18}/></div><div className="audience"><div className="donut"><div><strong>62%</strong><span>Mobile</span></div></div><div className="audience-list"><div><span><i className="dot mobile"/>Mobile</span><b>62%</b></div><div><span><i className="dot desktop"/>Desktop</span><b>31%</b></div><div><span><i className="dot tablet"/>Tablet</span><b>7%</b></div></div></div></div></section>
 </div>}
